---
- name: "Clone repository"
  git:
    repo: "{{ app_git_url }}"
    dest: /home/{{ app_name }}_deploy/{{ app_name }}

- name: "Install Crystal app dependencies"
  command:
    chdir: /home/{{ app_name }}_deploy/{{ app_name }}
    cmd: shards install --quiet --production

- name: "Install Yarn app dependencies"
  command:
    chdir: /home/{{ app_name }}_deploy/{{ app_name }}
    cmd: yarn install

- name: "Build application JS assets"
  command:
    chdir: /home/{{ app_name }}_deploy/{{ app_name }}
    cmd: yarn prod

- name: "Build temporary Lucky binary"
  command:
    chdir: /home/{{ app_name }}_deploy/{{ app_name }}
    cmd: crystal build --release src/start_server.cr -o tmp_start_server

- name: "Replace existing Lucky binary"
  command:
    chdir: /home/{{ app_name }}_deploy/{{ app_name }}
    cmd: mv --force tmp_start_server start_server

- name: "Remove temporary Lucky binary"
  file:
    path: /home/{{ app_name }}_deploy/{{ app_name }}/tmp_start_server
    state: absent

- name: "Write SystemD configuration"
  become: true
  blockinfile:
    path: "/etc/systemd/system/{{ app_name }}.service"
    create: yes
    mode: "u=rw,g=r,o=r"
    marker: "# {mark} ANSIBLE MANAGED SITE CONFIGURATION "
    block: |
      [Unit]
      Description={{ app_name }}
      After=nginx.service

      [Service]
      Type=simple
      Restart=always
      RestartSec=5s
      User={{ app_name }}_deploy
      Environment="LUCKY_ENV=production"
      Environment="NODE_ENV=production"
      Environment="SECRET_KEY_BASE={{ app_secret_key }}"
      Environment="SENTRY_DSN={{ sentry_dsn }}"
      Environment="HOST=127.0.0.1"
      Environment="PORT=5000"
      Environment="APP_DOMAIN={{ app_domain }}"
      WorkingDirectory=/home/{{ app_name }}_deploy/{{ app_name }}
      ExecStart=/home/{{ app_name }}_deploy/{{ app_name }}/start_server

      [Install]
      WantedBy=multi-user.target

- name: "Start up Lucky app service"
  become: true
  service:
    name: "{{ app_name }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
