version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: master

  - package-ecosystem: npm
    directory: "/"
    target-branch: master
    versioning-strategy: increase
