name: lucky-diff

services:
  - dockerfile_path: dockerfiles/webserver.Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: stephendolan/lucky_diff
    name: lucky-webserver
    envs:
      - key: LUCKY_ENV
        scope: RUN_TIME
        value: production
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: APP_DOMAIN
        scope: RUN_TIME
        value: luckydiff.com
