---
- name: Check if swap file exists
  stat:
    path: "{{ swapfile_path }}"
  register: swap_file_check
  tags:
    - swap.file.check

- name: Create swap file
  command:
    cmd: "fallocate -l 1G {{ swapfile_path }}"
    creates: "{{ swapfile_path }}"

- name: Change swap file permissions
  file:
    path: "{{ swapfile_path }}"
    owner: "{{ root_user }}"
    group: "{{ root_user }}"
    mode: "0600"

- name: Format swap file
  command:
    cmd: "mkswap {{ swapfile_path }}"
  when: not swap_file_check.stat.exists

- name: Turn on swap
  command:
    cmd: "swapon {{ swapfile_path }}"
  when: not swap_file_check.stat.exists

- name: Write swap entry in fstab
  mount:
    path: none
    src: "{{ swapfile_path }}"
    fstype: "swap"
    opts: "sw"
    state: present

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapfile_swappiness }}"
