---
- name: Create the deploy group
  group:
    name: deploy
    state: present

- name: Create the deploy user
  user:
    name: "{{ deploy_user }}"
    comment: User for application deployment
    append: yes
    shell: /bin/bash
    groups:
      - deploy
      - sudo

- name: Allow deploy group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%deploy"
    line: "%deploy ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s

- name: Add deploy user authorized SSH keys
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ item }}"
  with_items:
    - https://github.com/stephendolan.keys

- name: Add root user authorized SSH keys
  authorized_key:
    user: "{{ root_user }}"
    key: "{{ item }}"
  with_items:
    - https://github.com/stephendolan.keys
