---

# Set up all server installations
- hosts: all
  remote_user: "{{ deploy_user }}"
  environment:
    LUCKY_ENV: production
    SKIP_LUCKY_TASK_PRECOMPILATION: "1"
  roles:
    - lucky
    - nginx
