---
# Set up user accounts
- hosts: all
  remote_user: root
  become: true
  roles:
    - user_creation

# Install utilities for server management and troubleshooting
- hosts: all
  remote_user: "{{ app_name }}_deploy"
  become: true
  roles:
    - linux_utils

# Install NodeJS
- hosts: all
  remote_user: "{{ app_name }}_deploy"
  become: true
  roles:
    - geerlingguy.nodejs
  vars:
    nodejs_version: "12.x"

# Set up all server installations
- hosts: all
  remote_user: "{{ app_name }}_deploy"
  environment:
    LUCKY_ENV: production
    SKIP_LUCKY_TASK_PRECOMPILATION: "1"
    NODE_ENV: production
  roles:
    - yarn
    - crystal
    - lucky
    - nginx
