---
# Set up user accounts and swap memory
- hosts: all
  remote_user: "{{ root_user }}"
  become: true
  roles:
    - user_creation
    - swap_memory

# Install utilities for server management and troubleshooting
- hosts: all
  remote_user: "{{ deploy_user }}"
  become: true
  roles:
    - linux_utils

# Install NodeJS
- hosts: all
  remote_user: "{{ deploy_user }}"
  become: true
  roles:
    - geerlingguy.nodejs
  vars:
    nodejs_version: "12.x"

# Set up all server installations
- hosts: all
  remote_user: "{{ deploy_user }}"
  environment:
    LUCKY_ENV: production
    SKIP_LUCKY_TASK_PRECOMPILATION: "1"
  roles:
    - yarn
    - lucky
    - nginx
