name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Lucky App CI'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger Render.com deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK }}
